project: MiMiNavigator.xcodeproj
schemes:
  - MiMiNavigator

index_store_path: .build/index/store
skip_build: true

retain_public: false
retain_objc_accessible: true
retain_assign_only_properties: true
strict: true

report_exclude:
  - "^Tests/"
  - "^.*\\.xcodeproj/"
  - "^Resources/"
  - "^Generated/"
  - "^Build/"
  - "^\\.build/"
  - "^Pods/"
  - ".*\\.generated\\.swift$"
  - ".*\\+Generated\\.swift$"

exclude_targets:
  - "Pods"
  - "PackageDependencies"
  - "MiMiNavigatorTests"
