# MiMiNavigator / Periphery
project: MiMiNavigator.xcodeproj
schemes:
  - MiMiNavigator

clean_build: true
skip_build: false

retain_public: true
retain_objc_accessible: true
retain_assign_only_properties: true

strict: false
