project: MiMiNavigator.xcodeproj
workspace: MiMiNavigator.xcworkspace

schemes:
  - MiMiNavigator

analyze_targets:
  - MiMiNavigator

retain_public: true
retain_assign_only_properties: true
enable_test_target_analysis: true

retain_patterns:
  - ".*View$"
  - ".*Model$"
  - ".*Controller$"

exclude_targets:
  - MiMiNavigatorTests

exclude_files:
  - "Tests/*"
  - "Scripts/*"
  - "**/*.generated.swift"

report_exclude:
  - "Carthage/*"
  - "Pods/*"

format: xcode
strict: true