//
//  .prettyswift.yaml
//  MiMiNavigator
//
//  Created by Iakov Senatov on 07.07.2025.
//  Copyright © 2025 Senatov. All rights reserved.
//

lineLength: 133
tabSize: 4
useTabs: false
spaceAfterColon: true
spaceBeforeColon: true
spaceAroundOperators: true
spaceAfterComma: true
braceStyle: sameLine
lineBreakBeforeEachArgument: false
lineBreakBeforeEachGenericRequirement: false
collapseArgumentsIfPossible: true
indentWrappedArguments: true
alignColons: true
alignTypeDeclarations: true
blankLineBeforeReturn: true
blankLineBeforeMembers: true
removeTrailingWhitespace: true
ensureTrailingNewlineAtEOF: true
