name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: MiMiNavigator
  SCHEME: MiMiNavigator
  SDK: macosx
  DESTINATION: "platform=macOS,arch=x86_64"

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        echo "Setting up environment for $PROJECT_NAME"
        export PROJECT_NAME=$PROJECT_NAME
        export SCHEME=$SCHEME
        export SDK=$SDK
        export DESTINATION=$DESTINATION

    - name: Install dependencies (for local and GitHub Actions)
      run: |
        if [ "$CI" != "true" ]; then
          echo "Running locally: installing dependencies with Homebrew"
          brew install swiftlint swiftformat
        else
          echo "Running on GitHub Actions"
          brew install swiftlint swiftformat
        fi

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

    - name: Build project
      run: |
        xcodebuild clean build \
          -project $PROJECT_NAME.xcodeproj \
          -scheme $SCHEME \
          -sdk $SDK \
          -destination "$DESTINATION" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      shell: bash

    - name: Run tests
      run: |
        xcodebuild test \
          -project $PROJECT_NAME.xcodeproj \
          -scheme $SCHEME \
          -sdk $SDK \
          -destination "$DESTINATION" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      shell: bash

    - name: Run SwiftLint
      run: |
        swiftlint --strict || true

    - name: Run SwiftFormat
      run: |
        swiftformat . || true

    - name: Generate code coverage report
      run: |
        xcodebuild test \
          -project $PROJECT_NAME.xcodeproj \
          -scheme $SCHEME \
          -sdk $SDK \
          -enableCodeCoverage YES \
          -destination "$DESTINATION" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      continue-on-error: true

    - name: Upload code coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: build/reports/code_coverage/